version: 2
updates:
  # Enable version updates for database-agent
  - package-ecosystem: "pip"
    directory: "/database-agent"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "python"
      - "database-agent"
    reviewers:
      - "chilleregeravi"
    assignees:
      - "chilleregeravi"
    versioning-strategy: "increase"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Separate group for major updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for github-agent
  - package-ecosystem: "pip"
    directory: "/github-agent"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "python"
      - "github-agent"
    reviewers:
      - "chilleregeravi"
    assignees:
      - "chilleregeravi"
    versioning-strategy: "increase"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Separate group for major updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "chilleregeravi"
    assignees:
      - "chilleregeravi"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 3

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/github-agent"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "docker"
      - "github-agent"
    reviewers:
      - "chilleregeravi"
    assignees:
      - "chilleregeravi"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 2

  - package-ecosystem: "docker"
    directory: "/database-agent"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "docker"
      - "database-agent"
    reviewers:
      - "chilleregeravi"
    assignees:
      - "chilleregeravi"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 2

  # Enable version updates for DevContainer
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "docker"
      - "devcontainer"
    reviewers:
      - "chilleregeravi"
    assignees:
      - "chilleregeravi"
    commit-message:
      prefix: "devcontainer"
      include: "scope"
    open-pull-requests-limit: 2

  # Enable version updates for database-agent dev dependencies
  - package-ecosystem: "pip"
    directory: "/database-agent"
    requirements-file: "requirements-dev.txt"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "python"
      - "database-agent"
      - "dev-deps"
    reviewers:
      - "chilleregeravi"
    assignees:
      - "chilleregeravi"
    commit-message:
      prefix: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 2

  # Enable version updates for github-agent dev dependencies
  - package-ecosystem: "pip"
    directory: "/github-agent"
    requirements-file: "requirements-dev.txt"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "python"
      - "github-agent"
      - "dev-deps"
    reviewers:
      - "chilleregeravi"
    assignees:
      - "chilleregeravi"
    commit-message:
      prefix: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 2
