# Database Agent Makefile - delegates to root Makefile
.PHONY: test lint format clean install

# Delegate common commands to root Makefile
test:
	cd .. && make test-database

lint:
	cd .. && make lint

format:
	cd .. && make format

clean:
	cd .. && make clean

install:
	cd .. && make install-dev
