version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for requirements files in the `database-agent` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "python"
    # Set review requirements
    reviewers:
      - "chilleregeravi"
    # Set the version update strategy
    versioning-strategy: "auto"
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 10
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Add permissions for Dependabot
    commit-message:
      prefix: "pip"
      include: "scope"
    # Allow Dependabot to create PRs
    allow:
      - dependency-type: "all"
    # Set security update behavior
    security-updates-only: false
    # Set version update behavior
    version-update-strategy: "auto"
    # Set PR behavior
    pull-request-branch-name:
      separator: "-"
    # Set commit behavior
    commit-message:
      prefix: "pip"
      include: "scope" 