name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'database-agent/**'
      - 'github-agent/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'database-agent/**'
      - 'github-agent/**'

jobs:
  database-agent:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database-agent

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: './database-agent/requirements.txt'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check formatting with black
      run: |
        pip install black
        black . --check
    - name: Type check with mypy
      run: |
        pip install mypy
        mypy .
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./database-agent/coverage.xml
        fail_ci_if_error: true

  github-agent:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github-agent

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: './github-agent/requirements.txt'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check formatting with black
      run: |
        pip install black
        black . --check
    - name: Type check with mypy
      run: |
        pip install mypy
        mypy .
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./github-agent/coverage.xml
        fail_ci_if_error: true 