name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'database-agent/**'
      - 'github-agent/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'database-agent/**'
      - 'github-agent/**'

permissions:
  contents: read

jobs:
  setup-database-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  # Required for cache save operations
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'database-agent/requirements*.txt'

      - name: Install dependencies
        working-directory: database-agent
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Cache dependencies
        uses: actions/cache/save@v4
        with:
          path: database-agent/.venv
          key: ${{ runner.os }}-database-agent-venv-${{ hashFiles('database-agent/requirements*.txt') }}

  setup-github-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'github-agent/requirements*.txt'

      - name: Install dependencies
        working-directory: github-agent
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

  database-agent-checks:
    needs: setup-database-agent
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      actions: read  # Required for pip cache restore
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'database-agent/requirements*.txt'

      - name: Install dependencies
        working-directory: database-agent
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run linting checks
        working-directory: database-agent
        run: |
          ruff check .

      - name: Run tests with coverage
        working-directory: database-agent
        run: |
          pytest --cov=src --cov-report=xml --cov-fail-under=80

  github-agent-checks:
    needs: setup-github-agent
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read  # Required for pip cache restore
    defaults:
      run:
        working-directory: ./github-agent

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: './github-agent/requirements*.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Lint with ruff
        run: |
          ruff check .
      - name: Test with pytest
        env:
          PYTHONPATH: src
        run: |
          pytest --cov=src --cov-report=xml --cov-fail-under=80

  test-github-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read  # Required for pip cache restore
    services:
      qdrant:
        image: qdrant/qdrant:latest
        ports:
          - 6333:6333
          - 6334:6334

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'github-agent/requirements*.txt'

      - name: Install dependencies
        working-directory: github-agent
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run tests with coverage
        working-directory: github-agent
        run: |
          pytest -v --cov=src --cov-report=term-missing --cov-fail-under=80

      - name: Lint check
        working-directory: github-agent
        run: |
          ruff check .

  build-database-agent:
    needs: database-agent-checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build database-agent image
        working-directory: database-agent
        run: |
          docker build -t database-agent:test .

  build-github-agent:
    needs: github-agent-checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build github-agent image
        working-directory: github-agent
        run: |
          docker build -t github-agent:test .
