name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-database-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        working-directory: database-agent
        run: |
          ln -s ../Makefile.common Makefile
          make venv

      - name: Cache dependencies
        uses: actions/cache/save@v4
        with:
          path: .venv
          key: ${{ runner.os }}-database-agent-venv-${{ hashFiles('**/requirements.txt') }}

  setup-github-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        working-directory: github-agent
        run: |
          ln -s ../Makefile.common Makefile
          make venv

      - name: Cache dependencies
        uses: actions/cache/save@v4
        with:
          path: .venv
          key: ${{ runner.os }}-github-agent-venv-${{ hashFiles('**/requirements.txt') }}

  database-agent-checks:
    needs: setup-database-agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: ${{ runner.os }}-database-agent-venv-${{ hashFiles('**/requirements.txt') }}

      - name: Run linting and formatting checks
        working-directory: database-agent
        run: |
          source ../.venv/bin/activate
          make lint-check-all

      - name: Run type checking
        working-directory: database-agent
        run: |
          source ../.venv/bin/activate
          mypy src

      - name: Run tests with coverage
        working-directory: database-agent
        run: |
          source ../.venv/bin/activate
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./database-agent/coverage.xml
          fail_ci_if_error: true

  github-agent-checks:
    needs: setup-github-agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: ${{ runner.os }}-github-agent-venv-${{ hashFiles('**/requirements.txt') }}

      - name: Run linting and formatting checks
        working-directory: github-agent
        run: |
          source ../.venv/bin/activate
          make lint-check-all

      - name: Run type checking
        working-directory: github-agent
        run: |
          source ../.venv/bin/activate
          mypy src

      - name: Run tests with coverage
        working-directory: github-agent
        run: |
          source ../.venv/bin/activate
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./github-agent/coverage.xml
          fail_ci_if_error: true 